[manager]
prepend_keymap = [
  { on = "f", run = "plugin jump-to-char", desc = "Jump to char" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = 'l', run = 'plugin smart-enter', desc = "Enter the child directory, or open the file" },
  { on = ["g", "d"], run = 'cd ~/dev', desc = "Dev" },
]
