[manager]
linemode = 'size'

[opener]
edit = [
  { run = 'nvim $@', block = true, desc = "nvim (current selected)", for = "unix" },
  { run = 'nvim', block = true, desc = "nvim (cmd)", for = "unix" },
  { run = 'code %*', orphan = true, desc = "code", for = "windows" },
  { run = 'code -w %*', block = true, desc = "code (block)", for = "windows" },
]

[plugin]
prepend_fetchers = [
  { id = "git", name = "*", run = "git" },
  { id = "git", name = "*/", run = "git" },
]
