[manager]
linemode = 'size'

[opener]
edit = [
  { run = 'code $@', orphan = true, desc = "Command: code", for = "unix" },
  { run = 'code $@', orphan = true, desc = "Command: code", for = "windows" },
  { run = 'nvim $@', block = true, desc = "Command: nvim", for = "unix" },
]

[plugin]
prepend_fetchers = [
  { id = "git", name = "*", run = "git" },
  { id = "git", name = "*/", run = "git" },
]
